import type { Metadata } from "next";
import { FC } from "react";

export const metadata: Metadata = {
  title: "Create Next Layout Page",
  description: "Generated by custom snippet",
};

interface AuthLayoutPageProps {
  children: React.ReactNode;
}

const AuthLayoutPage: FC<AuthLayoutPageProps> = ({ children }) => {
  return (
    <main className="flex min-h-screen w-full justify-center items-center">
      {children}
    </main>
  );
};

export default AuthLayoutPage;
