import { NavigationSidebar } from "@/components/navigation/navigation-sidebar";
import type { Metadata } from "next";
import { FC } from "react";

export const metadata: Metadata = {
	title: "Create Next Layout Page",
	description: "Generated by custom snippet",
};

interface MainLayoutPageProps {
	children: React.ReactNode;
}

const MainLayoutPage: FC<MainLayoutPageProps> = ({ children }) => {
	return (
		<div className="h-full">
			<div className="hidden md:flex h-full w-[72px] z-30 flex-col fixed inset-y-0">
				<NavigationSidebar />
			</div>
			<main className="md:pl-[72px] h-full">{children}</main>
		</div>
	);
};

export default MainLayoutPage;
