import "@/styles/globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { FC } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/providers";
import { cn } from "@/lib/utils";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

interface RootLayoutProps {
	children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
	return (
		<html lang="en" className="dark" suppressHydrationWarning>
			<body className={cn(font.className, "bg-[#f5f5f5] dark:bg-[#313338]")}>
				<ClerkProvider>
					<Providers>{children}</Providers>
				</ClerkProvider>
			</body>
		</html>
	);
};

export default RootLayout;
